export const data = [
	{
		id: 1,
		nameProduct: 'Agua de romero',
		price: 75,
		quantity: 1,
		img: 'src/assets/images/Ms_RomeroV2.png',
		data1Product: '-Estimula el crecimiento y fortalece los folículos.',
		data2Product: '-Previene la caída.',
		data3Product: '-Aporta brillo y mejora la textura.',
	},
	{
		id: 2,
		nameProduct: 'Keratina',
		price: 95,
		quantity: 1,
		img: 'src/assets/images/Ms_Keratina.png',
		data1Product: '-Promueve la hidratación.',
		data2Product: '-Estimula el crecimiento.',
		data3Product: '-Mejora la elasticidad del cabello.',
		},
	{
		id: 3,
		nameProduct: 'Tratamiento de Jamaica',
		price: 75,
		quantity: 1,
		img: 'src/assets/images/Ms_Jamaica.png',
		data1Product: '-Repara -Hidrata.',
		data2Product: '-Nutre. -Fortalece.',
		data3Product: '-Restaura.',
	},
	{
		id: 4,
		nameProduct: 'Tratamiento de Linaza',
		price: 85,
		quantity: 1,
		img: 'src/assets/images/Ms_Linaza.png',
		data1Product: '-',
		data2Product: '-',
		data3Product: '-',
	},
	{
		id: 5,
		nameProduct: 'Tratamiento de aguacate',
		price: 85,
		quantity: 1,
		img: 'src/assets/images/Ms_Aguacate.png',
		data1Product: '-',
		data2Product: '-',
		data3Product: '-',
	},
	{
		id: 6,
		nameProduct: 'Tónico de romero, Canela y Jengibre',
		price: 80,
		quantity: 1,
		img: 'src/assets/images/Ms_Romero.png',
		data1Product: '-Aporta aceites esenciales.',
		data2Product: '-Vitaminas que previenen la caída del cabello.',
		data3Product: '-Fortalece la fibra capilar.',
	},
	  
	// Aquí pueden agregar más o modificar los productos existentes
];
