export const data = [
	{
		id: 1,
		nameProduct: 'Agua de romero',
		price: 800,
		quantity: 1,
		img: 'src/assets/images/rs.PNG',
		dataProduct: 'Laptop pantalla FHD de 13.3 pulgadas\nIntel Core i7-8665U hasta 3.8 GHz\n16 GB DDR4 RAM\n512 GB SSD\nHDMI\nWindows 11 Pro 64 bits\n(reacondicionada)',
	},
	{
		id: 2,
		nameProduct: 'Computadora',
		price: 1200,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/71kOeTL+2vL._AC_SL1500_.jpg',
		dataProduct: 'PC Gamer\nAMD Ryzen 4700S\n8 Cores 3.6 GHz\n16GB DDR4 RAM\nSSD 500GB\nMonitor 23.8\nWiFi Red',
	},
	{
		id: 3,
		nameProduct: 'Monitor',
		price: 200,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/51CWZt5r-QL._AC_SL1000_.jpg',
		dataProduct: 'Monitor 21.5" Pulgadas MG2221 LED\n Panel VA\nResolución Full HD 1920 x 1080\n75 Hz MAX\n4 ms de Tiempo de Respuesta\nConexiones HDMI y VGA.',
	},
	{
		id: 4,
		nameProduct: 'Teclado',
		price: 50,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/61Nt8geXzWL._AC_SL1500_.jpg',
		dataProduct: 'Teclado Gaming en inglés\nRGB LIGHTSYNC\nTeclas retroiluminadas\nResistente a Salpicaduras\nTeclas personalizables\nControles Multimedia Dedicados - Negro',
	},
	{
		id: 5,
		nameProduct: 'Ratón (mouse)',
		price: 30,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/61UxfXTUyvL._AC_SL1500_.jpg',
		dataProduct: 'Mouse Alámbrico 100\nCable de Conexión USB\nWindows/MAC OS\nNegro',
	},
	{
		id: 6,
		nameProduct: 'Impresora',
		price: 150,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/618YwpCpkVL._AC_SL1500_.jpg',
		dataProduct: 'Impresora Multifuncional\nColor\nImpresión\nCopiado\nEscaneado \nWiFi \n7FR21A',
	},
	{
		id: 7,
		nameProduct: 'Escáner',
		price: 100,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/61Cw62lE0YL._AC_SL1500_.jpg',
		dataProduct: 'Escáner de Documentos móvil\nCompacto dúplex\n(Reacondicionado Premium)',
	},
	{
		id: 8,
		nameProduct: 'Disco duro externo',
		price: 80,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/612IzIVNLCL.jpg',
		dataProduct: 'Disco Duro Externo Portátil\n4TB 2.5"\nUSB 3.1\nNegro',
	},
	{
		id: 9,
		nameProduct: 'Memoria USB',
		price: 20,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/71rlOrGekpL._AC_SL1500_.jpg',
		dataProduct: 'USB Data Traveler Exodia M\nCapacidad: 32GB\nUSB 3.2 Gen 1 (DTXM/32GB)',
	},
	{
		id: 10,
		nameProduct: 'Auriculares',
		price: 40,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/51HhYD53fML._AC_SL1500_.jpg',
		dataProduct: 'Audífonos Inalámbricos\nBluetooth 5.1\nAuriculares inalámbricos Impermeable\nSe Pueden Usar para Correr, Hablar por teléfono, Ver Videos, Escuchar música',
	},
	{
		id: 11,
		nameProduct: 'Altavoces',
		price: 60,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/61GZqsRmQVL._AC_SL1500_.jpg',
		dataProduct: 'Sistema de Audio con Subwoofer\nSonido Impactante\n40 W RMS\nGraves Potentes\nEntradas de 3.5 mm/RCA\nPC/PS4/Xbox/TV/Móvil/Tablet\nNegro',
	},
	{
		id: 12,
		nameProduct: 'Micrófono',
		price: 30,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/71nozlRTz3L._AC_SL1500_.jpg',
		dataProduct: 'Micrófono de condensador USB para PC\nPS4 y Mac LED rojo',
	},
	{
		id: 13,
		nameProduct: 'Cámara web',
		price: 50,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/61-6uAf8soL._AC_SX679_.jpg',
		dataProduct: 'HD Pro Webcam con Tapa de privacidad\nVideoconferencias 1080P FULL HD\nSonido Estéreo\nCorrección de Iluminación\nSkype/Google Hangouts/FaceTime\nPC/Mac/Android/Chromebook',
	},
	{
		id: 14,
		nameProduct: 'Tarjeta gráfica',
		price: 200,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/41XFzGbYo1L._AC_.jpg',
		dataProduct: ' 8GB GDDR6 128-bit 14 Gbps PCIE 4.0\nTarjeta gráfica para juegos\nrefrigeración avanzada IceStorm 2.0\nparada de ventilador congelado\ncontrol activo del ventilador',
	},
	{
		id: 15,
		nameProduct: 'Tarjeta de sonido',
		price: 80,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/61-AeJjmX2L._AC_SX679_.jpg',
		dataProduct: 'Tarjeta de sonido interna PCI-e para juegos y DAC\n24 bits/192 kHz\n116 dB SNR\nASIO\n600Ω amplificador de auriculares\necualizador de micrófono\ndiscreto 5.1 / virtual 7.1\nsoporta Dolby Digital Live\nDTS',
	},
	{
		id: 16,
		nameProduct: 'Router',
		price: 60,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/41WCJGODEtL._AC_SL1000_.jpg',
		dataProduct: ' WiFi 6 AX3000 WiFi Router - 802.11ax Router\nGigabit\nDual Band\nOFDMA\nMU-MIMO\nFunciona con Alexa',
	},
	{
		id: 17,
		nameProduct: 'Modem',
		price: 40,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/61CNrNCDVTL._AC_SL1000_.jpg',
		dataProduct: 'Internet portátil\nIncluye SIM con 5Ggb Gratis',
	},
	{
		id: 18,
		nameProduct: 'Switch de red',
		price: 80,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/51TZdJ6LjhL._AC_SL1000_.jpg',
		dataProduct: 'Unmanaged Switch de Escritorio\n8 Puertos 10/100/1000Mbps',
	},
	{
		id: 19,
		nameProduct: 'Adaptador de red inalámbrico',
		price: 30,
		quantity: 1,
		img: 'https://cdn1.coppel.com/images/catalog/mkp/133/3000/1331036-1.jpg',
		dataProduct: 'Adaptador USB Inalámbrico de WiFi\nBanda Doble de 600M (2.4G / 150Mbps + 5G / 433Mbps)\nUSB 2.0 Tarjeta Red WiFi Dongle con Antena de 2dBi\nReceptor WiFi para PC / Escritorio / Laptop / Tablet\nDual Band 2.4G / 5G 802.11 ac\nSoporte para Windows Linux Mac OS',
	},
	{
		id: 20,
		nameProduct: 'Cable HDMI a VGA',
		price: 10,
		quantity: 1,
		img: 'https://m.media-amazon.com/images/I/61frOm77AWL._AC_SL1462_.jpg',
		dataProduct: 'Adaptador HDMI a VGA con Audio de 3.5mm\nMicro USB Cable de Carga\n1080P Convertidor Adaptador Portátil para PC\nPortátiles\nHDTV Proyectores\nPS4/3 Xbox y Otros Dispositivos HDMI',
	},
	{
		id: 21,
		img: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
		nameProduct: 'Zapatos Nike',
		price: 80,
		quantity: 1,
		dataProduct: 'Nike Tenis para hombre\nAdobe/Velvet Brown-lt Crimson\n12 US',
	},
	{
		id: 22,
		img: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1099&q=80',
		nameProduct: 'Reloj',
		price: 50,
		quantity: 1,
		dataProduct: 'Reloj deportivo\nCasual de cuarzo medio de plástico y silicona para mujer',
	},
	{
		id: 23,
		img: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
		nameProduct: 'Smartwatch',
		price: 90,
		quantity: 1,
		dataProduct: 'Apple Watch Series 6 (GPS, 44 mm)\nFunda de aluminio gris espacial con correa deportiva negra',
	},
	{
		id: 24,
		img: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80',
		nameProduct: 'Perfume',
		price: 50,
		quantity: 1,
		dataProduct: 'CHANEL\nCOCO NOIR\nEAU DE PARFUM CON VAPORIZADOR',
	},
	{
		id: 25,
		img: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
		nameProduct: 'Audifonos',
		price: 20,
		quantity: 1,
		dataProduct: 'Audífonos inalámbricos\non-Ear WH-CH520 hasta 50 Horas de duración de batería\nNegro',
	},
	{
		id: 26,
		img: 'https://www.steren.com.mx/media/catalog/product/cache/b69086f136192bea7a4d681a8eaf533d/image/2062791e0/teclado-usb-gamer-xtreme.jpg',
		nameProduct: 'Teclado',
		price: 35,
		quantity: 1,
		dataProduct: 'Teclado gamer español de membrana\nTeclas silenciosas y rápidas con iluminación dinámica RGB\nResistente a derrames\nCompatible con Windows 10/8.1/8/7',
	},
	  
	// Aquí pueden agregar más o modificar los productos existentes
];
